[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "anti_gikes"
version = "0.1.0"
dependencies = [
    # Daftar dependensi dari requirements.txt
]
